---
title: "Project description"
---

## Timeline

[Topic ideas](#topic-ideas) due Fri, Feb 18

[Proposal](#project-proposal) due Fri, Mar 18

[Draft report](#draft-report) due Fri, Apr 8

[Peer review](#peer-review) due Fri, Apr 15

[Final report](#written-report) due Mon, Apr 25

[presentation + slides](#video-presentation--slides) and [final GitHub repo](#reproducibility---organization) due Thu, Apr 28

[Presentation comments](#presentation-comments) due Sat, Apr 30

## Introduction

**TL;DR**: *Create an exploratory analysis based on OpenStreetMap or American Community Survey data. That is your final project.*

The goal of the final project is for you to create an exploratory analysis using real world data. Students are encourages to use:

-   OpenStreetMap data (using the `{osmdata}` package),
-   American Community Survey data (using the `{tidycensus}` package),
-   or a combination of both sources.

Both data sources include varied types and topics so you can choose based on your interests or work you have done in other courses or research projects.

The goal of this project is for you to demonstrate your understanding of the skills we covered in this class (and beyond, if you like!) and apply them to a data set to analyze it in a meaningful way.

All analyses must be done in RStudio, and all components of the project **must be reproducible**.

### Logistics

You will work on the project with your lab groups.

The four primary deliverables for the final project are

-   A written, reproducible report detailing your analysis
-   A GitHub repository corresponding to your report
-   Slides + a video presentation
-   Formal peer review on another team's project
