---
title: "Week 2"
order: 2
subtitle: "Visualizing spatial data with `{ggplot2}`"
date: 2024-09-04
---

```{r}
#| echo: false
#| message: false
library(ggplot2)
```

## Overview

This week is all about making plots and maps using the `{ggplot}` package. Learning to visualize data is a great place for start learning how to exploring data analytically and understanding the value of tidy data when working with R.

### Key Objectives

-   Introduce the concept of a "pipe" (`%>%` or `|>`) and how and when to use it
-   Introduce the concept of the "grammar of graphics"
-   Practice plotting and mapping data with `{ggplot2}`
-   Practice mapping data with `{mapview}` (TODO: Make sure interactive maps are included in the slides/exercise)

### Key Skills

- Using keyboard shortcuts in RStudio (TODO: Add keyboard shortcut for a pipe and assignment operator)
- Creating plots using `ggplot()`, `aes()`, and `geom_()` functions
- Mapping spatial data using `geom_sf()` and `coord_sf()`
- Mapping spatial data using `mapview()`
- Using `theme_` functions to customize the appearance of a plot
- Using `labs()` to add labels to a plot

## Prepare

{{< include _readings_02.qmd >}}

## Participate

🖥️ [Visualizing spatial data with `{ggplot2}`](../slides/data-visualization)

## Practice

🛠️️ [Exercise 0{{< meta order >}}](../exercises/exercise_0{{< meta order >}}.qmd)
