---
title: "Effective visualization with `{ggplot2}` and R"
order: 15
---

## Where to start?

-   Know your goal
-   Know your audience
-   Know your format

## What next?

-   Choosing appropriate graphic types
-   Writing and formatting clear text
-   Selecting appropriate and engaging colors
-   Preparing your feature geometry appropriately

------------------------------------------------------------------------

Focus for today:

-   Working with `theme()` (and custom theme packages like [hrbrthemes](https://hrbrmstr.github.io/hrbrthemes/)) to customize plot appearance
-   Using [ragg](https://ragg.r-lib.org/) to use custom fonts with ggplot2
-   Working with [scales](https://scales.r-lib.org/) and `scale_` functions
-   Working with the [new legends features](https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/)

------------------------------------------------------------------------

Resources for ggplot2:

-   ["Drawing Anything with ggplot2" workshop materials](https://github.com/thomasp85/ggplot2_workshop) (2020)
-   [Best practices for programming with ggplot2 - Posit](https://posit.co/resources/videos/best-practices-for-programming-with-ggplot2/) (2020)
-   [Graphic Design with ggplot2 - Graphic Design with ggplot2](https://rstudio-conf-2022.github.io/ggplot2-graphic-design/) (2022)
-   [Engaging and Beautiful Data Visualizations with ggplot2](https://posit-conf-2023.github.io/dataviz-ggplot2/) (2023)

------------------------------------------------------------------------

Additional packages:

-   [patchwork](https://patchwork.data-imaginist.com/)
-   [ggforce](https://ggforce.data-imaginist.com/)
-   [ggplot2 extensions](https://exts.ggplot2.tidyverse.org/gallery/)

------------------------------------------------------------------------

Packages for interactive and animated plots:

-   [gganimate](https://gganimate.com/)
-   [plotly](https://plotly.com/r/)
-   [ggiraph](https://davidgohel.github.io/ggiraph/)

------------------------------------------------------------------------

Packages for interactive maps:

-   [rdeck](https://qfes.github.io/rdeck/)
-   [mapgl](https://walker-data.com/mapgl/)
-   [leaflet](https://rstudio.github.io/leaflet/)

------------------------------------------------------------------------

Packages for working with text:

-   [ggtext](https://wilkelab.org/ggtext/)
-   [marquee](https://marquee.r-lib.org/index.html)
-   [ggrepel](https://ggrepel.slowkow.com/)
-   [ggannotate](https://github.com/MattCowgill/ggannotate) (for interactively setting annotation locations)

------------------------------------------------------------------------

Packages for 3D data visualization:

-   [rayshader](https://www.rayshader.com/)

## Choosing appropriate graphic types

-   What makes one graphic, chart, plot, or map "better" or "worse"?

------------------------------------------------------------------------

What makes a bad map *bad*?

For new map makers who might not know any better, it is often:

-   Confusing or distracting layout
-   Not enough color contrast for features
-   Cluttered labels, legends, or features

------------------------------------------------------------------------

What makes a fine map *just* fine?

For more experienced map makers who might be in a hurry:

-   Not enough thought on font sizes and styling
-   No feature generalization (simplifying geometry where appropriate for the map scale or subject)
-   Inappropriate color scales

------------------------------------------------------------------------

There are many cartographic considerations that also apply to other all types of data visualization:

-   Layout
-   Fonts (Typography)
-   Colors
-   Output formats

------------------------------------------------------------------------

But there are also some cartographic considerations that apply to maps in special and important ways:

-   Feature geometry (and cartographic conventions)
-   Projections
-   Scaling

## Items, Attributes, Marks, and Channels

In [Visualization Analysis and Design](https://www.cs.ubc.ca/~tmm/vadbook/) (2014), Tamara Munzner describes a set of useful concepts:

-   items,
-   attributes,
-   links,
-   marks,
-   and channels

::: notes
Book website: https://www.cs.ubc.ca/\~tmm/vadbook/

via https://homepage.divms.uiowa.edu/\~luke/classes/STAT4580/percep.html
:::

## Items and Attributes

Items

:   basic units on which data is collected

Attributes

:   numerical or categorical features of the data items we want to represent

Links

:   relations among items, e.g. months within a year, or countries within a continent.

## Marks and Channels

Marks

:   geometric entities used to represent items: points, lines, areas.

Visual channels

:   features of marks that can be used to reflect values of attributes."

::: notes
https://homepage.divms.uiowa.edu/\~luke/classes/STAT4580/percep.html
:::
